In [5]:
import numpy as np
from os import listdir
import os
from os.path import isfile, join
from pathlib import Path


folder_path = "dataset/topo/embeddings/dnabert"


# list of files in the folder without the extension
IDs = [Path(f).stem for f in listdir(folder_path) if isfile(join(folder_path, f))]


embeddings_matrix = []


for id in IDs:

    # load the file as a numpy array
    raw_embedding = None
    try:
        raw_embedding = np.load(folder_path + "/" + id + ".npy")
        # print(raw_embedding.shape)
    except:
        raw_embedding = np.load(folder_path + "/" + id + ".npy", allow_pickle=True)
        print(f"Error while loading the embedding of sequence {id}")
        # os.remove(folder_path + "/" + id + ".npy")
        print(raw_embedding.shape)
        

In [6]:
import numpy as np
from os import listdir
from os.path import isfile, join
from pathlib import Path
from Bio import SeqIO


FASTA_FILE_PATH = "dataset/meningite/meningite.fasta"
lens = []

for count, seqrecord in enumerate(SeqIO.parse(FASTA_FILE_PATH, "fasta")):

    lens.append(len(str(seqrecord.seq)))

print(np.mean(lens))



2240049.3970588236


In [14]:

from Bio import SeqIO   
from os import listdir
from os.path import isfile, join
from pathlib import Path



records = list(SeqIO.parse("dataset/topo/topo.xml", "uniprot-xml"))

xml_names = []
for record in records:
    if 'CENPJ_MOUSE' in record.id or 'CENPJ_MOUSE' in record.name:
        print(record.id, record.name)
        

    name = f'{record.id}|{record.name}'  
    xml_names.append(name)

folder_path = 'dataset/topo/embeddings' + "/" + 'prose'

# list of files in the folder without the extension
IDs = [Path(f).stem for f in listdir(folder_path) if isfile(join(folder_path, f))]
IDs = [i[i.find("|")+1:] for i in IDs]

# check if the two lists are equals 
if set(IDs) == set(xml_names):
    print("The two lists are equal")




Q569L8 CENPJ_MOUSE
The two lists are equal


In [10]:
# generate a 8*10 random matrix

import numpy as np
import matplotlib.pyplot as plt


np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
print((np.random.rand(8, 10) - 0.5) * 3)

# print with only two decimal digits

 


[[0.38 0.09 -1.08 1.24 -1.12 -0.08 0.40 0.57 0.32 -0.06]
 [1.17 -1.02 0.69 0.53 1.45 -0.35 -0.62 -1.01 -0.02 -0.65]
 [0.95 -0.59 0.26 -1.37 -1.14 -1.38 0.74 1.45 0.55 -1.43]
 [-1.43 0.18 1.03 1.47 0.65 0.14 -0.97 0.01 0.33 -0.71]
 [0.03 -0.39 -0.88 0.65 0.56 1.23 -0.28 -1.42 -1.34 1.49]
 [-0.04 -1.44 -0.26 0.61 -1.09 1.47 -0.81 -1.27 0.92 -0.82]
 [-0.74 -0.10 -0.06 0.26 -0.72 -0.36 -0.13 -0.37 0.34 0.48]
 [1.10 0.54 1.41 0.69 -1.15 0.92 0.29 -0.97 0.48 0.89]]
